#!/usr/bin/env mksh
#
# === {{CMD}}
#
set -u -e -o pipefail

PATH="$PATH:$THIS_DIR/../my_os/bin"
PATH="$PATH:$THIS_DIR/../my_fs/bin"

cd "$THIS_DIR"

local +x IFS=$'\n'

my_os package --install streamlink

case "$(my_os name)" in
  "rolling_void")
    echo "=== Installing services:"
    my_fs link "$PWD"/runit/high                /var/service/nhk-high
    my_fs link "$PWD"/runit/low                 /var/service/nhk-low
    my_fs link "$PWD"/runit/recording-stream    /var/service/nhk-recording-stream
    my_fs link "$PWD"/runit/record-weekly-shows /var/service/nhk-record-weekly-shows
    ;;
esac


