#!/usr/bin/env mksh
#
#
set -u -e -o pipefail

PATH="$PATH:$PWD/bin"
my_media current
my_media title
my_media title next
my_media next
my_media meta-record $(my_media titles | cut -d':' -f1 | head -n1)

my_media seconds-left
my_media meta
my_media keys
