#!/usr/bin/env mksh
#
# === {{CMD}}
#
set -u -e -o pipefail

PATH="$PATH:$THIS_DIR/../my_fs/bin"
cd "$THIS_DIR"

case "$(echo $@)" in
  --clear)
    local +x FILES_FOUND=""
    local +x AGE="2"
    local +x IFS=$'\n'

    for FILE in $(find "tmp/schedules" "tmp/skips" -type f -mtime +"${AGE}" -print ) ; do
      local +x INFO="$(stat -c "%y:" $FILE) $FILE"
      if rm "$FILE" ; then
        FILES_FOUND="yes"
        echo "$INFO"
      fi
    done

    if [[ -z "$FILES_FOUND" ]]; then
      echo "=== No files found older than $AGE days." >&2
    fi
    ;;

  *)
    echo "!!! Unknown options: $@" >&2
    exit 2
    ;;

esac
