#!/usr/bin/env mksh
#
# === {{CMD}}
#
set -u -e -o pipefail

PATH="$PATH:$THIS_DIR/../my_fs/bin"
cd "$THIS_DIR"

case "$(echo $@)" in
  --clear)
    local +x FILES_FOUND=""
    local +x AGE="2"
    local +x IFS=$'\n'

    local +x OLD_SCHED="$(find "tmp/schedules" -type f -iname '*.json'  -print | sort | head -n-10)"
    if [[ ! -z "$OLD_SCHED" ]]; then
      for FILE in $(echo "$OLD_SCHED"); do
        echo "$(stat -c "%y" "$FILE"): $FILE"
        rm "$FILE"
      done
    fi

    for FILE in $(find "tmp/skips" -type f -mtime +"${AGE}" -print ) ; do
      local +x INFO="$(stat -c "%y" $FILE): $FILE"
      if rm "$FILE" ; then
        FILES_FOUND="yes"
        echo "$INFO"
      fi
    done

    if [[ -z "$FILES_FOUND" && -z "$OLD_SCHED" ]]; then
      echo "=== No files found older than $AGE days." >&2
    fi
    ;;

  *)
    echo "!!! Unknown options: $@" >&2
    exit 2
    ;;

esac
