#!/usr/bin/mksh
#
#

set -u -e # -o pipefail
PATH="$PATH:/apps/my_nhk/bin"
mkdir -p /tmp/nhk
NHK_LOG=/tmp/nhk/record-newsline

case "$(date +"%I:%M")" in
  "05:59"|"11:59")
    echo -n "--- Beginning to record @ "
    date +"%H:%M:%S"
    my_nhk record-next "NEWSLINE" || echo "error $?"
    ;;
esac
