#!/usr/bin/mksh
#
#

set -u -e -o pipefail
PATH="$PATH:/apps/my_nhk/bin"
while : ; do
  my_nhk record-next "COOL JAPAN|UKIYO-E|Doki|Document|Buzz|Focus|Melo|Newsroom|Close-up|Inside"
  sleep "$(( 60 * 25 ))" # === run every 30 minutes
done
