#!/usr/bin/mksh

local +x media_app=/usr/bin/streamlink
local +x CURL=/usr/bin/curl

if [[ -z "$@" ]]; then
  local +x DEFINITION="low"
else
  local +x DEFINITION="$1"; shift
fi

if [[ -z "$@" ]]; then
  PORT=2111
else
  PORT="$1"; shift
fi

if [[ ! -e "$media_app" ]]; then
  echo "--- Not found: $(basename $media_app)"
  exit 1
fi

if [[ ! -e "$CURL" ]]; then
  echo "--- Not found: $CURL"
  exit 1
fi

local +x FILE="http://www3.nhk.or.jp/nhkworld/app/tv/hlslive_web.xml"
local +x FILE="http://www3.nhk.or.jp/nhkworld/app/tv/hlslive_tv.xml"
local +x M3U8="$($CURL --silent "$FILE" | grep -Pzo "(?s)<${DEFINITION}_url>.+?<wstrm>\K(.+?)(?=</ws)" | tr -d '\000'|| :)"

if [[ -z "$M3U8" ]]; then
  echo "--- Could not retrieve: file: $FILE"
  exit 1
fi

# File from:
# http://www3.nhk.or.jp/nhkworld/app/tv/hlslive_tv.xml
exec $media_app       \
  --http-no-ssl-verify           \
  --player-external-http          \
  --player-external-http-port $PORT \
  "hlsvariant://$M3U8 name_key=bitrate"  best


